	SELECT DISTINCT br.customerNumber EmployeeID,br.vendorName AS "Employee Name",  br.USERDEFINEDID VendorCode1,ISNULL(cs.USERDEFINEDID,'') VendorCode2
    FROM [BR-CL-SQL3\MSSQLSERVER3].[NEIGHBORHOOD_CENTERS_INC].[dbo].[AP7VENDORS] br LEFT JOIN [BR-CL-SQL3\MSSQLSERVER3].[PROMISE_COMMUNITY_SCHOOL].[dbo].[AP7VENDORS] cs ON br.CUSTOMERNUMBER = cs.CUSTOMERNUMBER 
    WHERE ISNUMERIC(br.customerNumber) = 1

UNION 
	SELECT DISTINCT cs.customerNumber EmployeeID,cs.vendorName AS "Employee Name", cs.USERDEFINEDID VendorCode1, '' AS VendorCode2
	FROM [BR-CL-SQL3\MSSQLSERVER3].[PROMISE_COMMUNITY_SCHOOL].[dbo].[AP7VENDORS] cs 
	WHERE ISNUMERIC(cs.customerNumber) = 1 
        AND cs.CUSTOMERNUMBER NOT IN 
            (SELECT DISTINCT br2.CUSTOMERNUMBER FROM [BR-CL-SQL3\MSSQLSERVER3].[NEIGHBORHOOD_CENTERS_INC].[dbo].[AP7VENDORS] br2 
            JOIN [BR-CL-SQL3\MSSQLSERVER3].[PROMISE_COMMUNITY_SCHOOL].[dbo].[AP7VENDORS] cs2 ON br2.CUSTOMERNUMBER = cs2.CUSTOMERNUMBER 
            WHERE ISNUMERIC(br2.customerNumber) = 1)